stages:
  - build
  - deploy

# run this when nothing else runs
# to keep MRs working
dummy:
  stage: build
  image: alpine:latest
  script:
    - echo "placeholder"
  rules:
    - if: $CI_PIPELINE_SOURCE == 'merge_request_event'

# run this when it's a merge request just to ensure the book does build
check-book-builds:
  stage: build
  image:
    name: peaceiris/mdbook:latest
    entrypoint: [""]
  script:
    - /bin/sh -c "mdbook build documentation-book --dest-dir dist/documentation"
  rules:
    - if: $CI_PIPELINE_SOURCE == 'merge_request_event' && $CI_MERGE_REQUEST_TARGET_BRANCH_NAME == $CI_DEFAULT_BRANCH

# run this when it's a commit to main to build the book
build-book:
  stage: build
  image:
    name: peaceiris/mdbook:latest
    entrypoint: [""]
  script:
    - /bin/sh -c "mdbook build documentation-book --dest-dir dist/documentation"
  artifacts:
    paths:
      - dist/*
    expire_in: 1 hour
  rules:
    - if: $CI_COMMIT_BRANCH == $CI_DEFAULT_BRANCH

# run this when it's a commit to main to deploy the book
deploy-site:
  stage: deploy
  image: jfxs/wrangler:latest
  script:
    - npx wrangler pages deploy dist --project-name=$PROJECT_NAME --branch=main --commit-dirty=true
  rules:
    - if: $CI_COMMIT_BRANCH == $CI_DEFAULT_BRANCH
  needs:
    ["build-book"]
