stages:
  - build
  - deploy

build-site:
  stage: build
  image: node:latest
  script:
    - npm install --global pnpm@latest-10
    - pnpm install
  artifacts:
    paths:
      - node_modules/*
      - dist/*

build-book:
  stage: build
  image: peaceiris/mdbook:latest
  script:
    - cd documentation-book
    - mdbook build
  artifacts:
    paths:
      - documentation-book/book/*

deploy-site:
  stage: deploy
  image: jfxs/wrangler:latest
  script:
    - mkdir dist/documentation
    - mv documentation-book/book/* dist/documentation/
    - npx wrangler pages deploy dist --project-name=$PROJECT_NAME --branch=main
