stages:
  - build
  - deploy

build-book:
  stage: build
  image:
    name: peaceiris/mdbook:latest
    entrypoint: [""]
  script:
    - /bin/sh -c "mdbook build documentation-book --dest-dir dist/documentation"
  artifacts:
    paths:
      - dist/*

deploy-site:
  stage: deploy
  image: jfxs/wrangler:latest
  script:
    - npx wrangler pages deploy dist --project-name=$PROJECT_NAME --branch=main --commit-dirty=true
