[book]
title = "FreezeTag Documentation"
authors = ["Ethan Collier, Brayden Jonsson, Max Petersen, Sathya Tadinada"]
language = "en"

[output.html]
site-url = "/documentation/"
no-section-label = false

[output.html.fold]
enable = false    # whether or not to enable section folding
level = 0         # the depth to start folding
